### ISSUE TITLE
update code to use daemon/pidfile.py instead of gone pidlockfile

### ISSUE THREAD

**Issue by reedjc** [farsightsec/sie-update#10]
The code uses 
```
from daemon.pidlockfile import PIDLockFile
```
That python module code does not exist any more (including via pip).. It is in old Debian wheezy and Jessie, but it is not in Debian stretch packages. (I see online it is in various python-daemon 1.x versions.)

The python-daemon changed years ago:
https://pagure.io/python-daemon/c/56dc98767122c3378ba60bb3a2327057f65f121a
The pidfile.py file was added and pidlockfile.py was removed.
It now uses:
```
from lockfile.pidlockfile import PIDLockFile
```

Please adjust this code to use reflect this..  (I think we should have some tests to verify it works too.)

Maybe it can have some conditional to use the code it finds?

**Comment by cmikk** [comment]
See https://github.com/farsightsec/sie-update/pull/11

**Comment by reedjc** [comment]
#11 was merrged.
